name: prettier-check

on: [push]

jobs:
  check-prettier:
    name: check-prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Run prettier check
        run: |
          cd ./app
          npm ci
          npm run prettier:check
