name: prettier-check-finance-planner

on: [push]

jobs:
  prettier-check-finance-planner:
    name: prettier-check-finance-planner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run prettier check
        run: |
          cd ./finance-planner
          npm ci
          npm run prettier:check
