name: prettier-check

on: [push]

jobs:
  check-prettier:
    name: check-prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run prettier check
        run: |
          cd ./app
          npm ci
          npm run prettier:check
